### ISSUE TITLE
我有个很大的问题

### ISSUE THREAD

**Issue by BokaQin** [RealCorebb/bbPOV-V2#1]
我有一个小小的问题
我该如何做到把一段视频转成16进制的东东， 我是不是要把视频里的每一帧都剪出来之后来然后16进制处理呢？ 
之后是3d建模的原文件能分享吗，感恩不尽，想送这个东西给my mother，看看酷睿比比能否大公无私，感恩不尽

**Comment by RealCorebb** [comment]
是把gif转成16进制的，你应该先把视频转成gif，再利用python脚本进行转换，3D建模不能也不适合分享
